name: new_tuneflow
description: "A new Flutter project."
publish_to: "none"

# Update is dart code also
version: 1.4.5+45 # Update is dart code also
# Update is dart code also

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  ionicons: ^0.2.2
  gap: ^3.0.1
  dart_des: ^1.0.2
  page_transition: ^2.2.1
  blurrycontainer: ^2.1.0
  http: ^1.3.0
  parallax_animation: ^0.0.3
  flutter_staggered_grid_view: ^0.7.0
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2
  fluttertoast: ^8.2.12
  stream_transform: ^2.1.1
  path_provider: ^2.1.5
  device_info_plus: ^11.3.0
  image_picker: ^1.1.2
  flutter_easy_faq: ^1.0.1
  url_launcher: ^6.3.1
  web_socket_client: ^0.1.5
  clipboard: ^0.1.3
  share_plus: ^10.1.4
  firebase_messaging: ^15.2.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^6.2.2
  google_mobile_ads: ^5.3.1
  circular_seek_bar: ^1.1.1
  ticker_text: ^2.1.0
  in_app_update: ^4.2.3
  app_links: ^6.4.0
  flutter_svg: ^2.0.17
  easy_image_viewer: ^1.5.1
  in_app_purchase: ^3.2.1
  smooth_list_view: ^2.0.2
  readmore: ^3.0.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  equalizer_flutter:
    path: ./equalizer
  just_audio:
    path: ./just_audio
  audio_service: ^0.18.18
  firebase_crashlytics: ^4.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/
