// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbh_b4ST8E-jf3BYnduAk_8oWEf7GwtuM',
    appId: '1:1007722364128:android:744fd5d325d3ee89ce2485',
    messagingSenderId: '1007722364128',
    projectId: 'tuneflow-84bd7',
    storageBucket: 'tuneflow-84bd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJM1bPTlbwDyNXyXHoVet1bbkwPQslXZc',
    appId: '1:264191090501:ios:7afb9f9975e4aadc44a82c',
    messagingSenderId: '264191090501',
    projectId: 'tuneflow-75ee8',
    databaseURL: 'https://tuneflow-75ee8-default-rtdb.firebaseio.com',
    storageBucket: 'tuneflow-75ee8.appspot.com',
    iosClientId:
        '264191090501-p3354r615uuj260br9l3ggckjnmjcuq7.apps.googleusercontent.com',
    iosBundleId: 'com.tuneflow',
  );
}
